receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "dice_server"

  jaeger:
    endpoint: "0.0.0.0:14250"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]
